apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi-retain
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
