apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: laravel-env-secret
  # namespace: default
spec:
  encryptedData:
    .env: AgCb59llgegJhOHHs6Bj7jnlEyG/b+jz/t7XksK0810apzO94NEo8DpglhRbr27zC08xLCO8KuFLiO4uxRXf3uZ3TFwri1q83uygzE8OxYV8Yi2zS0g0dbBAW0H8FMJARAWnmAso/kEmHcKsJ1rlgmJOV8Y060PZt6yRezo3fp4bcPwf7WF0ILGV1n/69A8EoHjzHuwAA9bAoAxUb+JDfz7fdkXulcHOUh2dbn7LuhZ4IxSYImikG6dPrzmhvCOc3abMjDgovHzHRIKc2z9/+PNr1X8K8F3ZiB85dFrF3HA7EBlNwX74u4YPlj/LgwrRe1ml4ptwnKJsrzSnKrun3aCcRbUx6DLHhCs/xPR9dnFNMcGmmlWP4V8ZkniZEcoXNRe+/Gwjbx3aNF3QDkbLnT2QX+y6KoDHS+YBQMOvcaM3bvIQxD4kKcZaZPecAJP1P8IRXBvbfovfwxMf7171OFQBet6CRLKHl+3RhsoMo2ZoCXBBZtJtvc+Pg8gtz2sYqEF9tcK1JEgKcHvmmkIotaZRyZ1P9/UfO0f6kiOiIiLj6js/kVTrMZTjp4NFJZsY8ZgDNhBCJLOGU6/TU9ex9dI17S+J1jU0f0lFO4Faa5CwTJwCtTL66At+G7oSID1TzVq88ug+LjmXGAaiW16nCBM8ZiGQ0gNllYmH5AtoHc4+XhVgEXKtLmN87/vKZhzWj9TgqnEGfHFeEESOPmoeRpm6z9wWoj/UWXQiUSvFezaiYRMFCWN4YBz/8+e1miVQcrkxib12BhaYRtdyhUugmqp+O5SB55+KtrLkZ+yWASFQKdgJtfVGXTkknpzFVLLS6gI+73ozE+LhNK9yU3EDeMr8xvlNbe8nqhDao/mlErNSex4y4VCH6PD/7kyPfgwQuyqjeWjuWZj1nfJFlUTDmvSlNGj+C6PLDcybb488h63WJDkn+o0AFdjDq4fjh7w9fvVqbYGxrM5izaeq8fdT5s8U0s7GVJVjezbtfkxfV2r8nUNaCcMHkLXViFWEkVd9o3pm23PzuSLM7ysSWRvIOZoTiVjUqLmVIKA2jS/Mqr2tNwETtilmI1cmbl28UFceRVXGumArXAkiCBI/6gdvl7zTMLhB9wREqUrGhWlZ/5L6zEHj1aVLqRTo1jMxao1jaRmHlxQGyDDVBAfjkGXDvWou
  template:
    metadata:
      creationTimestamp: null
      name: laravel-env-secret
      # namespace: default
    type: Opaque
---
